config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#index'
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def posts_counter
    posts.count
  end

  def most_recent_posts
    posts.last(3)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @current_user = current_user
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1> List of Users </h1>
<section class="w-100 align-items-center" >
    <% @users.each do |user| %>        
          <%= link_to user_path(user) do %>
            <div class="d-flex align-items-center m-3 gap-5 text-decoration-none text-dark">
            <%= image_tag(user.photo || '', alt: "#{user.name}-avatar", class: "border border-dark p-5 border-3")%>
              <div class="border border-dark border-3 w-100  p-3">
                <h2 class="flex-grow-1 text-decoration-none"> <%= user.name %></h2>
                <div class="d-flex justify-content-end">
                  Number of posts:
                  <%= user.posts_counter || 0 %>
                </div>
              </div>
            </div> 
          <% end %>
    <% end %>
</section>

app/views/users/show.html.erb
<h1> Single User Page</h1>
<div class="d-flex align-items-center mb-3 gap-3 w-100">
  <div>
    <img src="<%= @user.photo %>" alt="user photo" class= "border border-dark border-5 p-5">
  </div>
  <div class=" border border-dark border-5 w-100 p-3">
    <h2 class="flex-grow-1 p-2"> <%= @user.name %></h2>
    <div class="d-flex justify-content-end">
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</div>

<div class="border border-dark border-5 mx-auto w-100 p-3 mb-3">
  <h2>Biography</h2>
  <p><%= @user.bio %></p>
</div>

<div>
  <% @user.most_recent_posts.each do |post| %>
    <div class="border border-dark border-5 mx-auto w-100 p-3 mb-3">
      <h2>Post #<%= post.id %></h2>
      <p><%= post.text %></p>

      <div class="d-flex justify-content-end">
        <span>Comments: <%= "#{post.comments_counter || 0 } "%></span>
        <span>, Likes: <%= "#{ post.likes_counter || 0 }"%></span>
      </div>
    </div>
  <% end %> 
  <div class="text-center mb-3">
    <a href=<%=user_posts_path(@user)%> class="btn btn-primary btn-outline-secondary text-dark">
    See All Posts
  </a>
  </div>
</div>