config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do 
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      post 'login', to: 'login#index'
      resources :users, only: [:index] do
        resources :posts, only: [:index] do
          resources :comments, only: [:index, :create]
        end
      end
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, foreign_key: :author_id, class_name: 'User'
  has_many :comments, foreign_key: :post_id, class_name: 'Comment', dependent: :destroy
  has_many :likes, foreign_key: :post_id, class_name: 'Like', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_counter
  after_destroy :update_post_counter
  def update_post_counter
    author.update(posts_counter: author.posts.count)
  end

  def most_recent_comments
    comments.last(5)
  end
end

app/controllers/api/v1/posts_controller.rb
require 'jwt'
class Api::V1::PostsController < Api::V1::ApplicationController
  before_action :find_user_prams
  def index
    if @user
      @posts = @user.posts.order(created_at: :asc)
      render json: @posts
    else
      render json: { status: 'Failure', error: 'Post Not Found' }
    end
  end

  private

  def find_user_prams
    @user = User.find(params[:user_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find_by(id: params[:user_id])
    # @user = User.includes(:posts, :comments).find(params[:user_id])
    @posts = @user.posts.includes(:comments).paginate(page: params[:page], per_page: 2)
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @comment = Comment.new
    @like = Like.new
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    @post.likes_counter = 0
    @post.comments_counter = 0
    return unless @post.save

    redirect_to user_posts_path
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    authorize! :destroy, @post
    if @post.destroy
      flash[:notice] = 'Post was successfully deleted.'
    else
      flash[:error] = 'Something went wrong'
    end
    redirect_to user_posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>List of Posts for a given spesfic User</h1>
<div class="d-flex align-items-center mb-3 gap-3 w-100">
  <div>
    <img src="<%= @user.photo %>" alt="user photo" class= "border border-dark border-5 p-5">
  </div>
  <div class=" border border-dark border-5 w-100 p-3">
    <h2 class="flex-grow-1 p-2"> <%= @user.name %></h2>
    <div class="d-flex justify-content-end">
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>
</div>

<div>
  <% @user.most_recent_posts.each do |post| %>
    <div class="border border-dark border-3 mx-auto w-100 p-3 mb-3 text-dark">
      <h3><%= link_to post.title, user_post_path(@user, post) %></h3>
      <p><%= post.text %></p>

      <div class="d-flex justify-content-between">
        <div>
          <%= form_with model: @like, url: user_post_likes_path(post_id: post.id) do |form| %>
            <%= form.submit "Like", class: "btn btn-outline-secondary"%>
          <% end %>
        </div>

        <div>
          <span>Comments: <%= "#{post.comments_counter || 0 }"%></span>
          <span>, Likes: <%= "#{post.likes_counter || 0 }"%></span>
        </div>

      </div>
    </div>

    <div class="border border-dark border-3 mx-auto w-100 p-3 mb-3">
      <h4 class="mb-3">Comments</h4>
      <% post.most_recent_comments.each do |comment| %>
        <div class="mb-3">
          <span><%= comment.author.name %>:</span>
          <span> <%= comment.text %></span>
        </div>  
      <% end %>
    </div>

  <% end %>
</div>

<div class="text-center mb-5">
  <% if @user.id == current_user.id %>
    <%= link_to "Create new post", new_user_post_path, class: "bg-dark btn btn-outline-secondary" %>
  <% end %>
</div>

<div class="d-flex align-items-center justify-content-center p-3 pagination">
  <%= will_paginate @posts %> 
</div>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= form_with model: @post, url: user_posts_path do |form| %>

  <div class="mb-3">
    <%= form.label :Title, class: "form-label" %>
    <%= form.text_field :title, placeholder: "post title", class: "form-control"  %>
  </div>
  <div class="mb-3">
    <%= form.label :text, class: "form-label" %>
    <%= form.text_area :text, placeholder: "post text...", class: "form-control form-control-lg" %>
  </div>
  <div>
    <%= form.submit "Create Post", class: "btn btn-outline-secondary" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<section>
  <div class="border border-dark border-3 mx-auto w-100 p-3 mb-3">
    <div class="d-flex justify-content-between align-items-center p3">
      <h2>
      Post #<%= @post.id %> by <%= @user.name %>
      </h2>
      <div>
        <span>Comments: <%= @post.comments_counter %></span>
        <span>, Likes: <%= @post.likes_counter %></span>
      </div>
    </div>

    <div>
      <p> <%= @post.text %></p>
    </div>
    <div>
    <% if @user.id == current_user.id %>
    <%= button_to "Delete Post", user_post_path, method: :delete, class: "bg-danger btn btn-outline-secondary" %>
    <% end %>
  </div>
  </div>

  <div class="border border-dark border-3 mx-auto w-100 p-3 mb-3">
     <% @post.most_recent_comments.each do |comment| %>
      <%= "#{comment.author.name}: #{comment.text}"%>
      <% if @user.id == current_user.id %>
      <%= button_to "Delete Comment", user_post_comment_path(@user, @post, comment), method: :delete, class: "bg-danger mt-1 btn btn-outline-secondary" %>
      <% end %>
     <% end %>
  </div>

  <div>
     <h3>Add a comment: </h3>
       <%= form_with model: @comment, url: user_post_comments_path(post_id: @post) do |form| %>
        <div>
          <%= form.text_area :text, placeholder: "Write new comment...", class: "form-control"%>
        </div>
        <%= form.submit "Add Comment", class: "bg-success btn btn-outline-secondary m-2" %>
      <% end %>
    </div>
</section>